baseURL = "https://photoblogshop.netlify.app/"
languageCode = "en-us"
title = "My photo site"

theme = "photoblog"

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$"]


[frontmatter]
  date = ['date', 'publishDate', 'lastmod']
  expiryDate = ['expiryDate']
  lastmod = [':git', 'lastmod', 'date', 'publishDate']
  publishDate = ['publishDate', 'date']
  
  
  


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
